# -*- coding: utf-8 -*-
"""President Obama's Automatic Dog Door.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIqO6_WF4xEZI68OBCfrMdHr2yjKnuoO
"""

# Load data di Google Drive
from google.colab import drive
drive.mount('/content/drive')

!wget -P /content/drive/MyDrive/data https://www.dropbox.com/s/6p1g7jmpr44rjdp/presidential_doggy_door.zip

#Mengekstrak File zip ke direktori
import zipfile,os
local_zip = '/content/drive/MyDrive/woksop/presidential_doggy_door.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content/drive/MyDrive/data/')
zip_ref.close()

#Mempersiapkan direktori untuk data training dan data validasi
base_dir = '/content/drive/MyDrive/data/presidential_doggy_door/'

#Mengecek direktori hasil ekstraksi
os.listdir(base_dir)

pip install tensorflow

from tensorflow import keras

base_model = keras.applications.VGG16(
    weights = 'imagenet',
    input_shape = (224, 224, 3),
    include_top = False
)

base_model.summary()

base_model.trainable = False

input = keras.Input(shape=(224, 224, 3))
x = base_model(input, training=False)
x = keras.layers.GlobalAveragePooling2D()(x)
output = keras.layers.Dense(1)(x)
model = keras.Model(input, output)

model.summary()

model.compile(loss=keras.losses.BinaryCrossentropy(from_logits=True), metrics=[keras.metrics.BinaryAccuracy()])

from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    samplewise_center=True,  # set each sample mean to 0
    rotation_range=10,  # randomly rotate images in the range (degrees, 0 to 180)
    zoom_range = 0.1, # Randomly zoom image
    rescale = 1./255, #rescalimage
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    vertical_flip = False
)

# load training dataset
train_data = datagen.flow_from_directory('/content/drive/MyDrive/data/presidential_doggy_door/train/',
                                       target_size=(224, 224),
                                       color_mode='rgb',
                                       class_mode='binary',
                                       batch_size=8)

valid_data = datagen.flow_from_directory('/content/drive/MyDrive/data/presidential_doggy_door/valid/',
                                      target_size=(224, 224),
                                      color_mode='rgb',
                                      class_mode='binary',
                                      batch_size=8)

history = model.fit(train_data, steps_per_epoch=5, validation_data=valid_data, epochs=20)

"""The error `PIL.UnidentifiedImageError: cannot identify image file` indicates that the `ImageDataGenerator` encountered a file in your dataset that it cannot recognize as an image. This could be due to corrupted files or files with incorrect extensions.

To diagnose this, we can iterate through the directories and try to open each file to see which one is causing the issue.
"""

import matplotlib.pyplot as plt

accur = history.history['binary_accuracy']
val_accur = history.history['val_binary_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(len(accur))

plt.figure(figsize=(12,8))
plt.subplot(2, 1, 1)
plt.plot(epochs, accur, 'b', label='Training accuracy')
plt.plot(epochs, val_accur, 'g', label='validation accuracy')
plt.title('trainig and validation accuracy')
plt.legend(loc=0)

plt.subplot(2, 1, 2)
plt.plot(epochs, loss, 'r', label='training loss')
plt.plot(epochs, val_loss, 'y', label='valodatoin loss')
plt.title('training and validation loss')
plt.legend(loc=0)

plt.show()

base_model.trainable = True
model.compile(optimizer=keras.optimizers.RMSprop(learning_rate= .00001),
              loss=keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=[keras.metrics.BinaryAccuracy()])

history2=model.fit(train_data, steps_per_epoch=10, validation_data=valid_data, epochs=20)

#Plot Akurasi dan Loss
import matplotlib.pyplot as plt

accur = history2.history['binary_accuracy']
val_accur = history2.history['val_binary_accuracy']
loss = history2.history['loss']
val_loss = history2.history['val_loss']

epochs = range(len(accur))

plt.figure(figsize=(12,8))
plt.subplot(2, 1, 1)
plt.plot(epochs, accur, 'b', label='Training accuracy')
plt.plot(epochs, val_accur, 'g', label='Validation accuracy')
plt.title('Training and validation accuracy Fine Tuning')
plt.legend(loc=0)


plt.subplot(2, 1, 2)
plt.plot(epochs, loss, 'r', label='Training loss')
plt.plot(epochs, val_loss, 'y', label='Validation loss')
plt.title('Training and validation loss Fine Tuning')
plt.legend(loc=0)


plt.show()

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from tensorflow.keras.preprocessing import image as image_utils
from tensorflow.keras.applications.imagenet_utils import preprocess_input

def show_image(image_path):
    image = mpimg.imread(image_path)
    plt.imshow(image)

def prediksi(image_path):
    show_image(image_path)
    image = image_utils.load_img(image_path, target_size=(224, 224))
    image = image_utils.img_to_array(image)
    image = image.reshape(1,224,224,3)
    image = preprocess_input(image)
    preds = model.predict(image)
    return preds

prediksi('/content/drive/MyDrive/data/presidential_doggy_door/valid/bo/bo_20.jpg')

prediksi('/content/drive/MyDrive/data/presidential_doggy_door/valid/not_bo/121.jpg')

prediksi('/content/drive/MyDrive/data/presidential_doggy_door/valid/not_bo/bobby.jpg')

"""# **`Gate funcion`**"""

def input_image(image_path):
    preds = prediksi(image_path)
    if preds[0] < 0:
        print('\nitu bo \n silahkan masuk')
    else:
        print('itu bukan bo \n Tidak boleh Masuk')

input_image('/content/drive/MyDrive/data/presidential_doggy_door/valid/not_bo/bobby.jpg')

input_image('/content/drive/MyDrive/data/presidential_doggy_door/valid/not_bo/bo_28.jpg')

presiden_dog('/content/drive/MyDrive/data/presidential_doggy_door/valid/not_bo/boo.jpeg')

input_image('/content/drive/MyDrive/husky.jpeg')